### ISSUE TITLE
Add a Kafka topic for generic JSON

### ISSUE THREAD

**Issue by timovdk** [DRIVER-EU/scenario-manager#108]
This topic provides a way to send multiple types of JSONs on one topic on Kafka. This could be a way to quickly add new types of messages that the server publishes without having to generate AVRO schemas.

- [x] Add new topic
- [x] Make sure new JSONs can be uploaded in the GUI
- [x] Make sure a user can select the Kafka topic that this JSON will be published on
- [x]  Make a 'generic message' input, that allows for uploading of .json files and publishing of that file on a selected Kafka topic (either scheduled inject or manual inject)

**Comment by erikvullings** [comment]
I am not sure what you want to do here? One topic = one schema = one type of JSON message. So we only need a JSON upload button (or very simple editor) to upload a generic JSON file, select a topic, and send it to that topic, assuming that the JSON is already in the format that Kafka accepts. Ideally, it would be great if we can check that the JSON is valid (using the AVRO validator, but without sending it to Kafka).
