### ISSUE TITLE
SSL reverse proxy support

### ISSUE THREAD

**Issue by cdanger** [DRIVER-EU/scenario-manager#47]
With a web browser, if we try to access the web UI behind the Traefik reverse proxy on the testbed, we have a blank page because the webapp is not designed to work behind a reverse proxy. However, a reverse proxy is required for communication security, i.e. SSL/TLS protection. You can test it with an Apache or NGINX (with SSL enabled) instead of Traefik to reproduce the issue outside the testbed.

**Comment by cdanger** [comment]
any progress on this?

**Comment by erikvullings** [comment]
In the [homepage](https://github.com/DRIVER-EU/homepage) project, a reverse proxy has been setup, that resolves this problem. Still looking for a cleaner solution so keeping this one open.

**Comment by erikvullings** [comment]
Using Apache, NGINX and KeyCloak, a working version has been setup. Basically, it leaves the home page open but protects each link. E.g. you need to have tmt access in order to access the tmt.
